#!/bin/sh

# Receives the first value and opens man.cx with it on $BROWSER

if [ -z "$1" ]; then
    echo "Usage: mon <command>"
    exit
fi

# Run the $BROWSER command
$BROWSER "https://man.cx/$1" &> /dev/null &
