#!/bin/sh

sudo docker run \
  --name treeline-postgres \
  -e POSTGRES_PASSWORD=strapi \
  -e POSTGRES_DB=strapi \
  -e POSTGRES_USER=strapi \
	-e PGDATA=/var/lib/postgresql/data/pgdata \
	-v /custom/mount:/var/lib/postgresql/data \
  -d postgres

